config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  # omniauth authentication
  get    '/login',                   to: 'sessions#login', as: :login
  match  '/auth/:provider/callback', to: 'sessions#validate', via: [:get, :post]
  get    '/logout',                  to: 'sessions#logout', as: :logout
  get    '/auth/failure',            to: 'sessions#failure'
  
  # clean cache items
  resources :cache, only: [:index, :update]

  # about page
  get '/about',        to: 'about#index'

  # ack
  get '/colophon',     to: 'main#colophon'

  # résumé
  get '/resume',       to: 'resume#index'
  get '/resume/clean', to: 'resume#clean'
  
  resources :links, only: [:index, :create, :destroy] do
    patch 'update_all', on: :collection
  end
  
  resources :experiences, except: [:new]
  
  resources :facets,      except: [:new]
  
  resources :favorites do
    post 'sort_favorites', on: :collection
    post 'sort_things',    on: :collection
  end
  
  resources :tabletop_games, except: [:show]

  resources :recent_games, only: [:new, :create,  :edit, :update, :destroy]

  get  '/goty/edit',                 to: 'goty#edit',               as: 'edit_goty'
  get  '/goty/:year',                to: 'goty#show',               as: 'goty'
  post '/goty/sort',                 to: 'goty#sort',               as: 'sort_goty'
  put  '/goty/update/:goty_game_id', to: 'goty#update_explanation', as: 'update_goty_game'
  put  '/goty/publish/:goty_id',     to: 'goty#update_published',   as: 'update_goty_published'


  # https://github.com/rails/rails/issues/671
  # http://techoctave.com/c7/posts/36-rails-3-0-rescue-from-routing-error-solution
  match '*path', to: "application#routing_error", via: :get
end

app/models/tabletop_game.rb
class TabletopGame < ApplicationRecord

  has_attached_file     :image,
                        styles: {
                          thumb: ["100x100>", :png],
                          default: ["300x300>", :png]
                        },
                        path: ":rails_root/public/tabletop_games/:attachment/:id/:style/:filename",
                        url: "/tabletop_games/:attachment/:id/:style/:filename"
  validates_attachment_content_type :image, content_type: [ 'image/png', 'image/jpg', 'image/jpeg', 'image/gif']

  validates_presence_of :name

  scope :sorted, -> {
    order('name asc')
  }

  def players_min
    players or return nil
    match = players_regex
    match or return nil
    return match[1]
  end

  def players_max
    players or return nil
    match = players_regex
    match or return nil
    if match[2]
      if match[2] == '+'
        return nil
      elsif (match[2] == '-') && match[3]
        return match[3]
      end
    end
    return match[1]
  end

  #private

  def players_regex
    players.match(/([0-9]+)(\-|\+)?([0-9]+)?/)
  end

end

app/controllers/tabletop_games_controller.rb
class TabletopGamesController < ApplicationController
  before_action   :is_admin?, except: :index
  before_action   { |c| c.page_title 'tabletop games' }

  # GET /tabletop_games
  def index
    @tabletop_games   = TabletopGame.sorted
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /tabletop_games
  def manage
    @tabletop_games = TabletopGame.sorted
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /tabletop_games/new
  def new
    @tabletop_game = TabletopGame.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /tabletop_games/1/edit
  def edit
    @tabletop_game = TabletopGame.find(params[:id])
  end

  # POST /tabletop_games
  def create
    @tabletop_game = TabletopGame.new(tabletop_game_params)
    respond_to do |format|
      if @tabletop_game.save
        Rails.cache.delete('tabletop_fetched')
        format.html { redirect_to tabletop_games_url, notice: 'TableTop game was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /tabletop_games/1
  def update
    @tabletop_game = TabletopGame.find(params[:id])
    respond_to do |format|
      if @tabletop_game.update(tabletop_game_params)
        Rails.cache.delete('tabletop_fetched')
        format.html { redirect_to tabletop_games_url, notice: 'TableTop game was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /tabletop_games/1
  def destroy
    @tabletop_game = TabletopGame.find(params[:id])
    @tabletop_game.destroy
    respond_to do |format|
      format.html { redirect_to tabletop_games_url, notice: 'TableTop game was successfully baleeted.' }
    end
  end

  private

  def tabletop_game_params
    params.require(:tabletop_game).permit(:expansions, :name, :other_info, :players, :bgg_url, :image)
  end

end

app/views/tabletop_games/_form.html.haml
= form_for(@tabletop_game) do |f|
  - if @tabletop_game.errors.any?
    #error_explanation
      %h2 #{pluralize(@tabletop_game.errors.size, "error")} prohibited this game from being saved:
      %ul
        - @tabletop_game.errors.full_messages.each do |msg|
          %li #{msg}

  .row.mb-3
    .col-sm-3
      = f.label :image, class: 'form-label'
    .col-sm-9
      = f.file_field :image, class: 'form-control'
      - if f.object.image?
        = image_tag f.object.image.url(:default), alt: f.object.name

  .row.mb-3
    .col-sm-3
      = f.label :name, class: 'form-label'
    .col-sm-9
      = f.text_field :name, class: 'form-control'

  .row.mb-3
    .col-sm-3
      = f.label :players, class: 'form-label'
    .col-sm-9
      = f.text_field :players, class: 'form-control'

  .row.mb-3
    .col-sm-3
      = f.label :bgg_url, 'BoardGameGeek', class: 'form-label'
    .col-sm-9
      = f.text_field :bgg_url, class: 'form-control'

  .row.mb-3
    .col-sm-3
      = f.label :other_info, class: 'form-label'
    .col-sm-9.large_textarea
      = f.text_area :other_info, class: 'form-control'

  .row.mb-3
    .col-sm-3
      = f.label :expansions, class: 'form-label'
    .col-sm-9.large_textarea
      = f.text_area :expansions, class: 'form-control'

  .centered
    = f.submit (f.object.new_record? ? 'Add' : 'Update')+" tabletop game", class: 'btn btn-primary'

app/views/tabletop_games/_table.html.haml
:ruby
  maxest_player_max = tabletop_games.collect{|t| t.players_max.to_i || -1}.max

%div{id: "tabletop_loading"}
  Loading information for #{tabletop_games.size} games(s)...

%div{id: "tabletop_loaded", class: 'hidden'}
  - filter_threshold = 3
  - col_count = 0
  - skipped_columns = []
  - filter_columns = []
  - sort_column = 0
  %table.table.table-striped{id: "tabletop_table", class: 'display'}
    - if tabletop_games.size > filter_threshold
      %tfoot.header-group
        %tr
          %th
            - # game image and name
          %th{colspan: 2}
            - # players
            - # info and expansions, but in colspan
          - if logged_in?
            %td
              - # management

    %thead
      %tr
        %th
          Game
          - sort_column = col_count
          - col_count += 1
        %th
          Players
          - filter_columns << col_count
          - col_count += 1
        %th
          Info
          - skipped_columns << col_count
          - col_count += 1
        - if logged_in?
          %td
            - skipped_columns << col_count
            - col_count += 1

    %tbody
      - tabletop_games.sort_by{|t| t.name}.each do |tabletop_game|
        %tr
          %td.game_name{'data-order': tabletop_game.name}
            - if tabletop_game.image?
              .game_image
                = image_tag tabletop_game.image.url(:thumb), alt: tabletop_game.name, class: "tabletop_thumb", id: "opener_tabletop_#{tabletop_game.id}_img"
            = link_to tabletop_game.name, '#', id: "opener_tabletop_#{tabletop_game.id}_name"
          :ruby
            filter_array = (tabletop_game.players_min.to_i..(tabletop_game.players_max ? tabletop_game.players_max.to_i : maxest_player_max)).to_a
            filter_string = ","+filter_array.join(',')+","
            tabletop_game.players_max or filter_string += "-1,"
          %td.player_count{'data-filter': filter_string, 'data-filter-min': tabletop_game.players_min, 'data-filter-max': tabletop_game.players_max}
            = tabletop_game.players
          %td.game_info
            .game_desc
              = simple_format tabletop_game.other_info
            - if !tabletop_game.expansions.blank?
              .expansions
                - expansions = tabletop_game.expansions.split( /\r?\n/ )
                .expansion_heading
                  Expansions
                %ul
                  - expansions.each do |expansion|
                    %li #{expansion}
            - if !tabletop_game.bgg_url.blank?
              .game_bgg
                = link_to 'See on BoardGameGeek', tabletop_game.bgg_url
          - if logged_in?
            %td
              %p
                = link_to 'edit', edit_tabletop_game_path(tabletop_game)
              %p
                = link_to 'destroy', tabletop_game, method: :delete, data: { confirm: "Are you sure you want to remove #{tabletop_game.name}?" }
        %dialog.fixed.game_details{id: "dialog_tabletop_#{tabletop_game.id}", title: tabletop_game.name}
          - if tabletop_game.image?
            .game_image
              = image_tag tabletop_game.image.url(:default), alt: tabletop_game.name
          .game_detail
            .game_name
              = tabletop_game.name
            - if !tabletop_game.players.blank?
              .game_players
                #{tabletop_game.players} players
            - if !tabletop_game.other_info.blank?
              .game_info
                = simple_format tabletop_game.other_info
            - if !tabletop_game.expansions.blank?
              .game_expansions
                %strong Expansions:
                - expansions = tabletop_game.expansions.split( /\r?\n/ )
                %ul
                  - expansions.each do |expansion|
                    %li #{expansion}
            - if !tabletop_game.bgg_url.blank?
              .game_bgg
                = link_to 'See on BoardGameGeek', tabletop_game.bgg_url
          = javascript_tag nonce: true do
            :plain
              var dialog_tabletop_#{tabletop_game.id} = document.querySelector("#dialog_tabletop_#{tabletop_game.id}");
              dialogPolyfill.registerDialog(dialog_tabletop_#{tabletop_game.id});
              $('#opener_tabletop_#{tabletop_game.id}_img').click(function(e) {
                dialog_tabletop_#{tabletop_game.id}.showModal();
                return false;
              });
              $('#opener_tabletop_#{tabletop_game.id}_name').click(function(e) {
                dialog_tabletop_#{tabletop_game.id}.showModal();
                return false;
              });
              const updateBackdrop_tabletop_#{tabletop_game.id} = (ev) => {
                if (ev && ev.target !== dialog_tabletop_#{tabletop_game.id}) {
                  return;
                }
                dialog_tabletop_#{tabletop_game.id}.close();
              };
              dialog_tabletop_#{tabletop_game.id}.addEventListener('click', updateBackdrop_tabletop_#{tabletop_game.id});

= javascript_tag nonce: true do
  :plain
    $(document).ready(function() {
      $('#tabletop_table').DataTable({
        "searching": #{(tabletop_games.size > filter_threshold) ? 'true' : 'false'},
        "stateSave": false,
        "order": [[#{sort_column}, 'asc']],
        "pageLength": 10,
        "aLengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, 'All']],
        "paginate": false,
        "info": true,
        "bAutoWidth": true,
        "columnDefs": [
          {
            "targets": [#{skipped_columns.join(',')}],
            "orderable": false
          }
        ],
        "language": {
          "emptyTable":       "No tabletop games to show",
          "info":             "Showing _START_ to _END_ of _TOTAL_ tabletop games",
          "infoEmpty":        "Showing 0 to 0 of 0 tabletop games",
          "infoFiltered":     "(filtered from _MAX_ total tabletop games)",
          "infoPostFix":      "",
          "lengthMenu":       "Show _MENU_ tabletop games",
          "zeroRecords":      "No matching tabletop games found"
        },
        initComplete: function () { // column filters
          this.api().columns([#{filter_columns.join(',')}]).every( function () {
            var column = this;

            var select = $('<select id="players"><option value=""></option></select>').on( 'change', function () {
              var val = $.fn.dataTable.util.escapeRegex(
                $(this).val()
              );
              column
                .search( val ? ','+val+',' : '', true, false )
                .draw();
              console.log("filtering column to "+val);
            } );
            var label = $('<label for="players">Players </label>');
            select.appendTo( label );
            label.appendTo( $(column.footer()) );

            // grab unique min values and add to dropdown
            var uniqueNums = [];
            column.nodes().each(function(td) {
              var filterValue = $(td).data('filter-min');
              if (filterValue && uniqueNums.indexOf(filterValue) === -1) {
                uniqueNums.push(filterValue);
              }
            });

            // grab unique min and max values and add range to dropdown
            column.nodes().each(function(td) {
              var filterValue = $(td).data('filter-max');
              if (filterValue && uniqueNums.indexOf(filterValue) === -1) {
                uniqueNums.push(filterValue);
              }
            });
            var sorted = uniqueNums.sort(function(a, b) { return a - b; });
            var min = sorted[0];
            var max = sorted[sorted.length-1];
            for (let i = min; i <= max; i++) {
              console.log('Appending '+i);
              select.append('<option value="' + i + '">' + i + '</option>');
            }
            select.append('<option value="' + -1 + '">No max</option>');
          })
        }
      });

      $('#tabletop_loading').hide();
      $('#tabletop_loaded').show();
    });

app/views/tabletop_games/edit.html.haml
= stylesheet_link_tag 'tabletop_games'

:ruby
  links = [
    link_to('remove game', @tabletop_game, method: :delete, data: { confirm: "Are you sure you want to remove #{@tabletop_game.name}?" }),
    link_to('view tabletop', tabletop_games_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Recent game navigation')

%h1 Editing TableTop game

= render 'form'

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Recent game navigation')

app/views/tabletop_games/index.html.haml
= stylesheet_link_tag 'tabletop_games'
= javascript_include_tag :datatables

- if logged_in?
  :ruby
    links = [link_to('add tabletop game', new_tabletop_game_path)]
  = scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Tabletop navigation')

%h1 TableTop games

= render 'table', tabletop_games: @tabletop_games.each

- if logged_in?
  :ruby
  = scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Tabletop navigation')

app/views/tabletop_games/new.html.haml
= stylesheet_link_tag 'tabletop_games'

:ruby
  links = [
    link_to('view tabletop', tabletop_games_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Recent game navigation')

%h1 New TableTop game

= render 'form'

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Recent game navigation')