config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  # omniauth authentication
  get    '/login',                   to: 'sessions#login', as: :login
  match  '/auth/:provider/callback', to: 'sessions#validate', via: [:get, :post]
  get    '/logout',                  to: 'sessions#logout', as: :logout
  get    '/auth/failure',            to: 'sessions#failure'
  
  # clean cache items
  resources :cache, only: [:index, :update]

  # about page
  get '/about',        to: 'about#index'

  # ack
  get '/colophon',     to: 'main#colophon'

  # résumé
  get '/resume',       to: 'resume#index'
  get '/resume/clean', to: 'resume#clean'
  
  resources :links, only: [:index, :create, :destroy] do
    patch 'update_all', on: :collection
  end
  
  resources :experiences, except: [:new]
  
  resources :facets,      except: [:new]
  
  resources :favorites do
    post 'sort_favorites', on: :collection
    post 'sort_things',    on: :collection
  end
  
  resources :tabletop_games, except: [:show]

  resources :recent_games, only: [:new, :create,  :edit, :update, :destroy]

  get  '/goty/edit',                 to: 'goty#edit',               as: 'edit_goty'
  get  '/goty/:year',                to: 'goty#show',               as: 'goty'
  post '/goty/sort',                 to: 'goty#sort',               as: 'sort_goty'
  put  '/goty/update/:goty_game_id', to: 'goty#update_explanation', as: 'update_goty_game'
  put  '/goty/publish/:goty_id',     to: 'goty#update_published',   as: 'update_goty_published'


  # https://github.com/rails/rails/issues/671
  # http://techoctave.com/c7/posts/36-rails-3-0-rescue-from-routing-error-solution
  match '*path', to: "application#routing_error", via: :get
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  has_many  :favorite_things, dependent: :destroy
  accepts_nested_attributes_for :favorite_things, reject_if: proc { |attributes| attributes['thing'].blank? }, allow_destroy: true
  
  validates_presence_of :favorite_type
  validates_length_of   :favorite_type, maximum: 24
  
  validates_presence_of     :sort
  validates_numericality_of :sort
  
  scope :sorted, -> {
    order("#{Favorite.table_name}.sort asc, #{Favorite.table_name}.favorite_type asc")
  }
  scope :with_things, -> { includes(:favorite_things) }
  scope :with_type, lambda { |type|
    where(favorite_type: type)
  }
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action   :is_admin?
  before_action   { |c| c.page_title 'favorite management' }
   
  # GET /favorites
  def index
    @favorites = Favorite.sorted.with_things
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
    @favorite.sort = Favorite.last.sort + 1
    1.upto(NUM_FAVS) { |n| @favorite.favorite_things.build(sort: n) }
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
    things = @favorite.favorite_things.size
    if things < NUM_FAVS
      (things+1).upto(NUM_FAVS) { |n| @favorite.favorite_things.build(sort: n) }
    end
  end

  # POST /favorites
  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.sort = Favorite.all.size+1
    respond_to do |format|
      if @favorite.save
        Rails.cache.delete('things_fetched')
        format.html { redirect_to favorites_url, notice: 'Favorite was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /favorites/sort
  def sort_favorites
    id_order = params[:favorite_ids]
    logger.debug "************ resorting favorites as #{id_order.inspect}..."
    id_order.each_with_index do |id, index|
      logger.debug "************ id #{id} to order #{index}..."
      Favorite.update(id, sort: index)
    end
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorites re-ordered.' }
      format.js   { render nothing: true }
    end
  end

  # PUT /favorites/sort
  def sort_things
    id_order = params[:thing_ids]
    logger.debug "************ resorting things as #{id_order.inspect}..."
    id_order.each_with_index do |id, index|
      logger.debug "************ id #{id} to order #{index}..."
      FavoriteThing.update(id, sort: index)
    end
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite things re-ordered.' }
      format.js   { render nothing: true }
    end
  end

  # PUT /favorites/1
  def update
    @favorite = Favorite.find(params[:id])
    respond_to do |format|
      if @favorite.update(favorite_params)
        Rails.cache.delete('things_fetched')
        format.html { redirect_to favorites_url, notice: 'Favorite was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /favorites/1
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.js
    end
  end


  private

  def favorite_params
    params.require(:favorite).permit(:favorite_type, favorite_things_attributes: [:id, :thing, :link, :image, :_destroy])
  end
  
end

app/views/favorites/_form.html.haml
= form_for(@favorite) do |f|
  - if @favorite.errors.any?
    #error_explanation
      %h2 #{pluralize(@favorite.errors.size, "error")} prohibited this favorite from being saved:
      %ul
        - @favorite.errors.full_messages.each do |msg|
          %li #{msg}

  .row.mb-5
    .col-sm-3
      = f.label :favorite_type, class: 'form-label'
    .col-sm-9
      = f.text_field :favorite_type, class: 'form-control', required: true, autocomplete: 'off', data: {'1p-ignore': true}

  = f.fields_for :favorite_things, @favorite.favorite_things.sorted do |ft|
    .row.mt-2.mb-2.pt-3.pb-3.thing_form
      .col-sm-2
        - if ft.object.image?
          = image_tag ft.object.image.url(:thumb), alt: ft.object.thing

      .col-sm-10
        .row.mb-1
          .col-sm-2
            = ft.label :thing, 'Thing', class: 'form-label'
          .col-sm-10
            = ft.text_field :thing, class: 'form-control'

        .row.mb-1
          .col-sm-2
            = ft.label :link, class: 'form-label'
          .col-sm-10
            = ft.text_field :link, class: 'form-control'

        .row.mb-1
          .col-sm-2
            = ft.label :image, class: 'form-label'
          .col-sm-10
            = ft.file_field :image, class: 'form-control'

        - unless ft.object.new_record?
          .row.mb-1
            .col-sm-10
            .col-sm-2
              .form-check
                = ft.label '_destroy', 'Remove', class: 'form-check-label'
                = ft.check_box '_destroy', class: 'form-check-input'
          
  .centered
    = f.submit (f.object.new_record? ? 'Add' : 'Update')+' favorite', class: 'btn btn-primary'

app/views/favorites/destroy.js.erb
$('#favorite_<%= @favorite.id %>').hide();

app/views/favorites/edit.html.haml
= stylesheet_link_tag 'favorites'

:ruby
  links = [
    link_to('remove favorite', @favorite, data: { confirm: "Are you sure you want to delete your #{@favorite.favorite_type} favorites?" }, method: :delete, remote: true),
    link_to('view favorites', favorites_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Favorites navigation')

%h2 Editing favorite

= render 'form'

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Favorites navigation')

app/views/favorites/index.html.haml
= stylesheet_link_tag 'favorites'

:ruby
  links = [link_to('add favorite', new_favorite_path)]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Favorites navigation')

%h1 Current favorites

#favorites
  - @favorites.each do |favorite|
    .sort_favorite.row.mb-5{'data-id': favorite.id}
      .col-1.drag
        = image_tag 'drag-indicator.svg', alt: 'drag to reorder favorites'
      .col-10
        %strong #{favorite.favorite_type}
        .sort_favorite_things.ms-3.mt-2{id: "favorites_#{favorite.id}"}
          - favorite.favorite_things.sorted.each do |thing|
            .sort_thing.row.mb-2{'data-id': thing.id}
              .col-1.nested_drag
                = image_tag 'drag-indicator.svg', alt: 'drag to reorder things'
              .col-10
                = thing.link ? link_to(thing.thing, thing.link) : thing.thing
        %ul.item_navigation
          %li
            = link_to 'edit', edit_favorite_path(favorite)
          %li
            = link_to('destroy', favorite, data: { confirm: "Are you sure you want to delete your #{favorite.favorite_type} favorites?" }, method: :delete, remote: true)

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Favorites navigation')

= javascript_include_tag :favorites

app/views/favorites/new.html.haml
= stylesheet_link_tag 'favorites'

:ruby
  links = [link_to('view favorites', favorites_path)]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Favorites navigation')

%h1 New favorite

= render 'form'

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Favorites navigation')