config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  # omniauth authentication
  get    '/login',                   to: 'sessions#login', as: :login
  match  '/auth/:provider/callback', to: 'sessions#validate', via: [:get, :post]
  get    '/logout',                  to: 'sessions#logout', as: :logout
  get    '/auth/failure',            to: 'sessions#failure'
  
  # clean cache items
  resources :cache, only: [:index, :update]

  # about page
  get '/about',        to: 'about#index'

  # ack
  get '/colophon',     to: 'main#colophon'

  # résumé
  get '/resume',       to: 'resume#index'
  get '/resume/clean', to: 'resume#clean'
  
  resources :links, only: [:index, :create, :destroy] do
    patch 'update_all', on: :collection
  end
  
  resources :experiences, except: [:new]
  
  resources :facets,      except: [:new]
  
  resources :favorites do
    post 'sort_favorites', on: :collection
    post 'sort_things',    on: :collection
  end
  
  resources :tabletop_games, except: [:show]

  resources :recent_games, only: [:new, :create,  :edit, :update, :destroy]

  get  '/goty/edit',                 to: 'goty#edit',               as: 'edit_goty'
  get  '/goty/:year',                to: 'goty#show',               as: 'goty'
  post '/goty/sort',                 to: 'goty#sort',               as: 'sort_goty'
  put  '/goty/update/:goty_game_id', to: 'goty#update_explanation', as: 'update_goty_game'
  put  '/goty/publish/:goty_id',     to: 'goty#update_published',   as: 'update_goty_published'


  # https://github.com/rails/rails/issues/671
  # http://techoctave.com/c7/posts/36-rails-3-0-rescue-from-routing-error-solution
  match '*path', to: "application#routing_error", via: :get
end

app/models/experience.rb
class Experience < ApplicationRecord
  validates_presence_of :title
  validates_length_of   :title, maximum: 60
  
  validates_presence_of :affiliation
  validates_length_of   :affiliation, maximum: 60
  
  validates_length_of   :affiliation_link, maximum: 90,      allow_nil: true, allow_blank: true
  validates_format_of   :affiliation_link, with: URI.regexp, allow_nil: true, allow_blank: true
  
  validates_length_of   :location, maximum: 60, allow_nil: true, allow_blank: true
  
  validates_presence_of :start_date
  
  scope :sorted, -> {
    order('start_date desc')
  }
  
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action   :is_admin?
  before_action   { |c| c.page_title 'experience management' }
  
  # GET /experiences
  def index
    @experiences = Experience.sorted
    @experience ||= Experience.new
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /experiences/1
  def show
    @experience = Experience.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /experiences/1/edit
  def edit
    @experience = Experience.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /experience
  def create
    @experience = Experience.new(experience_params)
    respond_to do |format|
      if @experience.save
        flash[:notice] = 'Experience added.'
        format.html { redirect_to experiences_url }
        format.js
      else
        flash[:error] = 'Experience not valid: '+@experience.errors.full_messages.join(', ')
        format.html { render action: "index" }
        format.js   { render action: "error" }
      end
    end
  end

  # PUT /experiences/1
  def update
    @experience = Experience.find(params[:id])

    respond_to do |format|
      if @experience.update(experience_params)
        flash[:notice] = 'Experience was successfully updated.'
        format.html { redirect_to experiences_url }
        format.js
      else
        flash[:error] = 'Experience not saved: '+@experience.errors.full_messages.join(', ')
        format.html { render action: "edit" }
        format.js   { render action: "update_error" }
      end
    end
  end

  # DELETE /experiences/1
  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.js   
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:start_date, :end_date, :title, :affiliation, :affiliation_link, :location, :tasks)
  end
  
end

app/views/experiences/_edit.html.haml
= form_for @experience, remote: true do |f|
  #experience
    = render 'form', f: f, experience: @experience
  .centered
    = submit_tag "Update", class: 'btn btn-primary'
  %ul.item_navigation
    %li
      = link_to 'cancel', @experience, remote: true

app/views/experiences/_form.html.haml
- if experience.errors.any?
  #error_explanation
    %h2 #{pluralize(experience.errors.size, "error")} prohibited this experience from being saved:
    %ul
      - experience.errors.full_messages.each do |msg|
        %li #{msg}

.row.mb-3
  .col-sm-3
    = f.label :title, 'Job title', class: 'form-label'
  .col-sm-9
    = f.text_field :title, class: 'form-control'
  
.row.mb-3
  .col-sm-3
    = f.label :affiliation, 'Workplace', class: 'form-label'
  .col-sm-9
    = f.text_field :affiliation, class: 'form-control'

.row.mb-3
  .col-sm-3
    = f.label :affiliation_link, 'Link', class: 'form-label'
  .col-sm-9
    = f.text_field :affiliation_link, class: 'form-control'

.row.mb-3
  .col-sm-3
    = f.label :location, class: 'form-label'
  .col-sm-9
    = f.text_field :location, class: 'form-control'
  
.row.mb-3
  .col-sm-3
    = f.label :start_date, class: 'form-label'
  .col-sm-9
    = f.date_field :start_date, class: 'form-control'
   
.row.mb-3
  .col-sm-3
    = f.label :end_date, class: 'form-label'
  .col-sm-9
    = f.date_field :end_date, class: 'form-control'
  
.row.mb-3
  .col-sm-3
    = f.label :tasks, class: 'form-label'
  .col-sm-9.large_textarea
    = f.text_area :tasks, class: 'form-control'

app/views/experiences/_show.html.haml
%div{ id: "notification_#{experience.id}" }
.exp[experience]
  = render 'view', experience: experience

app/views/experiences/_view.html.haml
.exp_metadata
  .left
    %p
      %strong #{experience.title}
    %p
      %em
        = experience.affiliation_link ? link_to(experience.affiliation, experience.affiliation_link): experience.affiliation
  .right
    %p #{experience.start_date.to_fs(:resume_date)} ~ #{experience.end_date ? experience.end_date.to_fs(:resume_date) : "present"}
    %p #{experience.location}
  .clear
- if !experience.tasks.blank?
  .tasks
    %ul
      - experience.tasks.split("\n").each do |task|
        %li
          = sanitize task, tags: %w(a strong em u), attributes: %w(href target name title src alt class)
%ul.item_navigation
  %li
    = link_to 'edit', edit_experience_path(experience), remote: true
  %li
    = link_to('delete', experience, data: { confirm: "Are you sure you want to delete #{experience.title} @ #{experience.affiliation}?" }, method: :delete, remote: true)

app/views/experiences/create.js.erb
notify("<%= escape_javascript(flash.discard(:notice)) %>");
$('#experiences').append("<%= escape_javascript(render('show', experience: @experience)) %>");
$('#new_exp')[0].reset();

app/views/experiences/destroy.js.erb
$('#experience_<%= @experience.id %>').hide();
$('#notification_<%= @experience.id %>').hide();
$('#notification').hide();

app/views/experiences/edit.html.haml
= stylesheet_link_tag 'experiences'

:ruby
  links = [
    link_to('experience list', experiences_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Experience navigation')

%h1 Editing experience

= render 'edit', experience: @experience

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Experience navigation')

app/views/experiences/edit.js.erb
$('#experience_<%= @experience.id %>').html("<%= escape_javascript(render 'edit', experience: @experience) %>");
$('#notification_<%= @experience.id %>').hide();
$('#notification').hide();

app/views/experiences/index.html.haml
= stylesheet_link_tag 'experiences'

- if @experiences && @experiences.size > 0
  %h1 Current experiences
  #experiences
  - @experiences.each do |experience|
    = render 'show', experience: experience

- if @experience
  %h1 New experience
  #notification
  = form_for :experience, html: {id: 'new_exp'}, remote: true do
    %div.exp#experience
      = fields_for @experience do |create|
        = render 'form', f: create, experience: @experience
    .centered
      = submit_tag "Add", class: 'btn btn-primary'

app/views/experiences/show.html.haml
= stylesheet_link_tag 'experiences'

:ruby
  links = [
    link_to('experience list', experiences_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Experience navigation')

= render 'show', experience: @experience

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Experience navigation')

app/views/experiences/show.js.erb
$('#experience_<%= @experience.id %>').html("<%= escape_javascript(render 'view', experience: @experience) %>");
$('#notification_<%= @experience.id %>').hide();
$('#notification').hide();

app/views/experiences/update.js.erb
notify("<%= escape_javascript(flash.discard(:notice)) %>", 'notice', '#notification_<%= @experience.id %>');
$('#experience_<%= @experience.id %>').html("<%= escape_javascript(render 'view', experience: @experience) %>");
$('#notification').hide();

app/views/experiences/update_error.js.erb
notify("<%= escape_javascript(flash.discard(:error)) %>", 'error', '#notification_<%= @experience.id %>');
$('#notification').hide();