config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  # omniauth authentication
  get    '/login',                   to: 'sessions#login', as: :login
  match  '/auth/:provider/callback', to: 'sessions#validate', via: [:get, :post]
  get    '/logout',                  to: 'sessions#logout', as: :logout
  get    '/auth/failure',            to: 'sessions#failure'
  
  # clean cache items
  resources :cache, only: [:index, :update]

  # about page
  get '/about',        to: 'about#index'

  # ack
  get '/colophon',     to: 'main#colophon'

  # résumé
  get '/resume',       to: 'resume#index'
  get '/resume/clean', to: 'resume#clean'
  
  resources :links, only: [:index, :create, :destroy] do
    patch 'update_all', on: :collection
  end
  
  resources :experiences, except: [:new]
  
  resources :facets,      except: [:new]
  
  resources :favorites do
    post 'sort_favorites', on: :collection
    post 'sort_things',    on: :collection
  end
  
  resources :tabletop_games, except: [:show]

  resources :recent_games, only: [:new, :create,  :edit, :update, :destroy]

  get  '/goty/edit',                 to: 'goty#edit',               as: 'edit_goty'
  get  '/goty/:year',                to: 'goty#show',               as: 'goty'
  post '/goty/sort',                 to: 'goty#sort',               as: 'sort_goty'
  put  '/goty/update/:goty_game_id', to: 'goty#update_explanation', as: 'update_goty_game'
  put  '/goty/publish/:goty_id',     to: 'goty#update_published',   as: 'update_goty_published'


  # https://github.com/rails/rails/issues/671
  # http://techoctave.com/c7/posts/36-rails-3-0-rescue-from-routing-error-solution
  match '*path', to: "application#routing_error", via: :get
end

app/models/recent_game.rb
class RecentGame < ApplicationRecord

  NINTENDO_PLATFORMS =  [
                          'Switch 2',
                          'Switch',
                          '3DS',
                          'GBA',
                          'SNES',
                          'NES'
                        ]
  PSN_PLATFORMS =       [
                          'PlayStation',
                          'PS5',
                          'PS4'
                        ]
  STEAM_PLATFORMS =     [
                          'Steam'
                        ]
  XBOX_PLATFORMS =      [
                          'Xbox',
                          'Xbox Series X/S',
                          'Xbox One',
                          'Xbox 360'
                        ]
  PLATFORMS = PSN_PLATFORMS + XBOX_PLATFORMS + NINTENDO_PLATFORMS + STEAM_PLATFORMS + ['Mac', 'the internet', 'iOS']

  has_attached_file     :image,
                        styles: {
                          thumb: ["100x100>", :png],
                          default: ["300x300>", :png]
                        },
                        path: ":rails_root/public/recent_games/:attachment/:id/:style/:filename",
                        url: "/recent_games/:attachment/:id/:style/:filename"
  validates_attachment_content_type :image, content_type: [ 'image/png', 'image/jpg', 'image/jpeg', 'image/gif']
  
  validates_presence_of :name
  validates_length_of   :name, maximum: 72

  validates_presence_of :platform
  validates_length_of   :platform, maximum: 15

  validates_presence_of :last_played
  
  validates_length_of   :url, maximum: 75, allow_blank: true, allow_nil: true
  validates_format_of   :url, with: URI.regexp, allow_blank: true, allow_nil: true
  
  scope :sorted, -> {
    order('last_played desc, updated_at desc')
  }
  scope :visible, -> {
    where(hidden: false)
  }
  scope :by_name, lambda { |name|
    where(name: name)
  }
  scope :on_platform, lambda { |platform|
    platforms = case platform
                when 'psn'
                  PSN_PLATFORMS
                when 'xbox'
                  XBOX_PLATFORMS
                when 'steam'
                  STEAM_PLATFORMS
                when 'switch'
                  NINTENDO_PLATFORMS
                end
    where(platform: platforms)
  }
  scope :with_image, -> {
    where('image_file_name is not null')
  }
  scope :goty_eligible, -> {
    year = Date.today.year
    where(release_year: year).
    where('created_at <= ?', Time.new(year,12,31,23,59))
  }

end

app/controllers/recent_games_controller.rb
class RecentGamesController < ApplicationController
  before_action   :is_admin?
  before_action   { |c| c.page_title 'recent games' }

  # GET /recent_games/new
  def new
    @recent_games = RecentGame.sorted
    @recent_game = RecentGame.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /recent_games/1/edit
  def edit
    @recent_game = RecentGame.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /recent_games
  def create
    @recent_game = RecentGame.new(recent_game_params)
    respond_to do |format|
      if @recent_game.save
        Rails.cache.delete('gaming_expiry')
        format.html { redirect_to new_recent_game_url, notice: 'Recent game was successfully added.' }
      else
        @recent_games = RecentGame.sorted
        format.html { render action: "new" }
      end
    end
  end

  # PUT /recent_games/1
  def update
    @recent_game = RecentGame.find(params[:id])

    respond_to do |format|
      if @recent_game.update(recent_game_params)
        flash[:notice] = 'Recent game was successfully updated.'
        Rails.cache.delete('gaming_expiry')
        format.html { redirect_to new_recent_game_url }
        format.js
      else
        flash[:error] = 'Recent game not saved: '+@recent_game.errors.full_messages.join(', ')
        format.html { render action: "edit" }
        format.js   { render action: "update_error" }
      end
    end
  end

  # DELETE /recent_games/1
  def destroy
    @recent_game = RecentGame.find(params[:id])
    @recent_game.destroy
    respond_to do |format|
      Rails.cache.delete('gaming_expiry')
      format.html { redirect_to new_recent_game_url, notice: 'Recent game was successfully baleeted.' }
    end
  end

  private

  def recent_game_params
    params.require(:recent_game).permit(:name, :platform, :last_played, :url, :hidden, :release_year, :image)
  end

end

app/views/recent_games/_form.html.haml
= form_for(@recent_game) do |f|
  - if @recent_game.errors.any?
    #error_explanation
      %h2 #{pluralize(@recent_game.errors.size, "error")} prohibited this game from being saved:
      %ul
        - @recent_game.errors.full_messages.each do |msg|
          %li #{msg}

  .row.mb-3
    .col-sm-2
      = f.label :name, class: 'form-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control', required: true, autocomplete: 'off', data: {'1p-ignore': true}

  .row.mb-3
    .col-sm-2
      = f.label :platform, class: 'form-label'
    .col-sm-10
      = f.select :platform, RecentGame::PLATFORMS, {}, class: 'form-select', required: true

  .row.mb-3
    .col-sm-2
      = f.label :last_played, 'Played', class: 'form-label'
    .col-sm-10
      = f.datetime_field :last_played, default: Time.now, class: 'form-control', required: true

  .row.mb-3
    .col-sm-2
      = f.label :release_year, 'Release year', class: 'form-label'
    .col-sm-10
      = f.number_field :release_year, class: 'form-control'

  .row.mb-3
    .col-sm-2
      = f.label :url, class: 'form-label'
    .col-sm-10
      = f.text_field :url, class: 'form-control'

  .row.mb-3
    .col-sm-2
      = f.label :hidden, 'Hidden?', class: 'form-check-label'
    .col-sm-10
      .form-switch
        = f.check_box :hidden, class: 'form-check-input', role: 'switch'

  .row.mb-3
    .col-sm-2
      = f.label :image, class: 'form-label'
    .col-sm-10
      = f.file_field :image, class: 'form-control'
      %br
      - if @recent_game.image?
        = image_tag @recent_game.image.url(:default), alt: @recent_game.name

  .centered
    = f.submit submit_label, class: 'btn btn-primary'

app/views/recent_games/edit.html.haml
= stylesheet_link_tag 'recent_games'

:ruby
  links = [
    link_to('remove game', @recent_game, method: :delete, data: { confirm: "Are you sure you want to remove #{@recent_game.name}?" }),
    link_to('view games', new_recent_game_path)
  ]
= scaffold_navigation(links: links, additional_class: 'mb-3', label: 'Recent game navigation')

%h1 Update a recent game

= render 'form', submit_label: "Update game"

= scaffold_navigation(links: links, additional_class: 'mt-3', label: 'Recent game navigation')

app/views/recent_games/new.html.haml
= stylesheet_link_tag 'recent_games'
= stylesheet_link_tag 'goty'

%h1 Add a recent game

= render 'form', submit_label: "Add game"

%h1 Recent game history

- if @recent_games
  #recent_games
    - @recent_games.each do |game|
      .row.mb-3.game{class: game.hidden? ? 'hidden_game' : ''}
        .row
          .col-sm-2.gaming_image
            - if game.image?
              = image_tag game.image.url(:thumb), alt: game.name, align: 'left', hspace: 10
            - else
              = image_tag("game-controller.png", alt: 'placeholder image', width: 100, height: 100)
          .col-sm-9.gaming_details
            .row
              .time
                = game.last_played.to_fs(:precise)
              .name
                = game.name
                - if game.release_year
                  .year
                    (#{game.release_year})
              .platform
                = game.platform
            - if game.achievement_name
              .row.mt-2.pt-2.gaming_achievement
                .achievement_name
                  = game.achievement_name
                - if game.achievement_time
                  .achievement_time
                    = game.achievement_time.to_fs(:precise)
                - if game.achievement_desc
                  .achievement_desc
                    = game.achievement_desc
        .row
          %ul.item_navigation
            %li
              = link_to 'edit', edit_recent_game_path(game)
            %li
              = link_to 'remove', game, method: :delete, data: { confirm: "Are you sure you want to remove #{game.name}?" }
- else
  %p There haven't been any recent games added yet.